<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Horo Server API Index</title>
    <!-- Import Google Icon Font -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Let browser know website is optimized for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="/bower_components/materialize/dist/css/materialize.min.css?fc=1Nxlcq6">
    <!-- Customized for horo-server -->
    <link rel="stylesheet" href="/custom/custom.css">
</head>
<body>
<header>
    <nav class="top-nav amber darken-3">
        <div class="container">
            <div class="nav-wrapper"><a class="page-title">Dev.Horo <small class="hide-on-small-only">Horo in your Kernel</small></a></div>
        </div>
    </nav>
</header>
<main class="container">
    <ul id="slide-out" class="side-nav fixed">
        <li class="top"></li>
        <li><a href="https://wiki.yoitsu.moe/wiki/Portal:Dev.horo" class="waves-effect"><i class="material-icons">info_outline</i>Project wiki</a></li>
        <li><a href="https://github.com/VOID001/dev.horo" class="waves-effect"><i class="material-icons">get_app</i>Download Now</a></li>
        <li><div class="divider"></div></li>
        <li><a class="subheader">Horo status</a></li>
        <?php foreach ($stats as $name => $info) { ?>
            <li><a class="waves-effect" href="#!"><span class="new badge" data-badge-caption=""><?= $info ?></span><?= $name ?></a></li>
        <?php } ?>
    </ul>
    <div class="hide-on-large-only">
        <div class="row center">
          <p class="hide-on-med-and-up">Horo in your Kernel</p>
          <a href="https://wiki.yoitsu.moe/wiki/Portal:Dev.horo" class="btn-large waves-effect blue">Project Wiki</a>
          <a href="https://github.com/VOID001/dev.horo" class="btn-large waves-effect white black-text">Download Now</a>
        </div>
        <div class="card">
            <div class="card-content">
                <span class="card-title">Horo status</span>
                <div class="collection">
                    <?php foreach ($stats as $name => $info) { ?>
                         <a href="#!" class="collection-item"><span class="new badge" data-badge-caption=""><?= $info ?></span><?= $name ?></a>
                    <?php } ?>
                </div>
            </div>
         </div>
     </div>
    <?php if (isset($users[0]) && $users[0]!= NULL) {?>
        <div class="card">
            <div class="card-content">
                <span class="card-title">Master (food) Overview</span>
                <table>
                    <thead>
                    <?php foreach ($users[0] as $key => $val) {?>
                        <th><?= $key ?></th>
                    <?php } ?>
                    </thead>
                    <tbody>
                    <?php for ($i = 0; $i < count($users); $i++){ ?>
                        <tr>
                            <?php foreach ($users[$i] as $key => $val) {?>
                                <td><?= $val ?></td>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                    <tbody>
                </table>
               </div>
           </div>
    <?php } ?>
</main>
<!-- footer 
<footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                 <ul>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                 </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
        © 2014 Copyright Text
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
    </div>
</footer>
-->
<script src="/bower_components/jquery/dist/jquery.min.js"></script>
<script src="/bower_components/materialize/dist/js/materialize.min.js"></script>
<script src="/custom/custom.js"></script>
</body>
</html>
